### ISSUE TITLE
Can't create a new Flutter project

### ISSUE THREAD

**Issue by vstokarev** [beansoftapp/flutter-storm-support#5]
PhpStorm 2020.2
FlutterStorm 2020.2.3
Paid subscription.
Flutter 1.20.1
Dart 2.9.0

Can't create a new project (and can't even stop the process of creation, because there's no Cancel button anywhere).
Can't copy error message, so please look at the screenshot:
<img width="1065" alt="Screen Shot 2020-08-08 at 1 24 33 PM" src="https://user-images.githubusercontent.com/6095904/89719198-b25e8d80-d97a-11ea-83a0-238abf2b6a51.png">

**Comment by vstokarev** [comment]
Closed the project and tried to open it - didn't work, just opens empty IDE window, where absolutely all the buttons are disabled and nothing is clickable.

**Comment by beansoft** [comment]
I'll take a look at it.

**Comment by vstokarev** [comment]
Thank you.
After I restarted IDE I was able to start using the project, so I can confirm the issue applies to project creation process only.

**Comment by beansoft** [comment]
I can't reproduce it, and i noticed there is something reporting about pub get failed(server unavailable).  I suggest you try to create a project again for sure not the network issue blocks the create process.

But still i'd like to improve the project create progress to avoid blocking the whole IDE window.

What's done in a new project creation process:
1. flutter --no-color create --offline --template app --description "A new Flutter project." --org com.example layout_basics
Recreating project layout_basics...
2. flutter internals run the pub get command (seems your problem is in the phase)
3. If everything done with no error, a flutter doctor is executed.

Also the red error is something same like here: https://github.com/flutter/flutter/issues/21338

Here is my log:

`flutter --no-color create --offline --template app --description "A new Flutter project." --org com.example layout_basics
Recreating project layout_basics...
  layout_basics/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  layout_basics/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  layout_basics/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  layout_basics/ios/Runner/Info.plist (created)
  layout_basics/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  layout_basics/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  layout_basics/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  layout_basics/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  layout_basics/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  layout_basics/ios/Runner/Base.lproj/Main.storyboard (created)
  layout_basics/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  layout_basics/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  layout_basics/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  layout_basics/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  layout_basics/ios/Flutter/Debug.xcconfig (created)
  layout_basics/ios/Flutter/Release.xcconfig (created)
  layout_basics/ios/Flutter/AppFrameworkInfo.plist (created)
  layout_basics/ios/.gitignore (created)
  layout_basics/test/widget_test.dart (created)
  layout_basics/layout_basics.iml (created)
  layout_basics/.gitignore (created)
  layout_basics/.metadata (created)
  layout_basics/android/app/src/profile/AndroidManifest.xml (created)
  layout_basics/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  layout_basics/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  layout_basics/android/app/src/main/res/drawable/launch_background.xml (created)
  layout_basics/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  layout_basics/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  layout_basics/android/app/src/main/res/values/styles.xml (created)
  layout_basics/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  layout_basics/android/app/src/main/AndroidManifest.xml (created)
  layout_basics/android/app/src/debug/AndroidManifest.xml (created)
  layout_basics/android/gradle/wrapper/gradle-wrapper.properties (created)
  layout_basics/android/gradle.properties (created)
  layout_basics/android/.gitignore (created)
  layout_basics/android/settings.gradle (created)
  layout_basics/android/app/build.gradle (created)
  layout_basics/android/app/src/main/kotlin/com/example/layout_basics/MainActivity.kt (created)
  layout_basics/android/build.gradle (created)
  layout_basics/android/layout_basics_android.iml (created)
  layout_basics/pubspec.yaml (created)
  layout_basics/README.md (created)
  layout_basics/ios/Runner/Runner-Bridging-Header.h (created)
  layout_basics/ios/Runner/AppDelegate.swift (created)
  layout_basics/ios/Runner.xcodeproj/project.pbxproj (created)
  layout_basics/lib/main.dart (created)
  layout_basics/.idea/runConfigurations/main_dart.xml (created)
  layout_basics/.idea/libraries/Flutter_for_Android.xml (created)
  layout_basics/.idea/libraries/Dart_SDK.xml (created)
  layout_basics/.idea/libraries/KotlinJavaRuntime.xml (created)
  layout_basics/.idea/modules.xml (created)
Running "flutter pub get" in layout_basics...                       1.1s
Wrote 71 files.

All done!
[✓] Flutter: is fully installed. (Channel stable, v1.17.5, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices: is not installed.
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.4)
[!] Android Studio: is partially installed; more components are available. (version 4.0)
[!] IntelliJ IDEA Ultimate Edition: is partially installed; more components are available. (version 2020.1.1)
[!] IntelliJ IDEA Community Edition: is partially installed; more components are available. (version 2020.2)
[!] Connected device: is not available.

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd layout_basics
  $ flutter run

Your application code is in layout_basics/lib/main.dart.

Process finished with exit code 0`

**Comment by beansoft** [comment]
I do noticed that if close the wifi and create project using online mode, the whole window blocks with nothing displayed. So thank you and i'll improve the progress when there slow or no network when creating new project.

**Comment by beansoft** [comment]
@vstokarev The blocking UI when create new flutter project  bug has been fixed, and I'd like invite you to do a test(it'll be approved in 2 days by Jetbrains)

Please download and install from disk to have a try:

 https://plugins.jetbrains.com/files/14718/94262/flutter-storm.zip?updateId=94262&pluginId=14718&family=INTELLIJ

What’s New
2020.2.4
Remove blocking UI and improvement stability when create new flutter project on *Storm IDE
Preview project images as an icon in your project explorer, supports png, svg, jpg, etc

**Comment by vstokarev** [comment]
Just tried to create a new project using an updated plugin. Everything worked as expected, I didn't see any issues. 
Thank you so much!
